/**
 * v1.3.0 Compliance Engine - Japanese Labor Standards Act Article 36 Agreement Monitoring
 * 労働基準法第36条（時間外労働協定）監視システム
 */

import Database from './database.js';

// 36協定関連の型定義
export interface LaborAgreement {
  id: string;
  companyId: string;
  agreementType: '36_standard' | '36_special' | 'other';
  effectiveFrom: Date;
  effectiveTo: Date;
  monthlyOvertimeLimit: number;      // 月間時間外労働上限
  yearlyOvertimeLimit: number;       // 年間時間外労働上限
  specialMonthlyLimit: number;       // 特別条項月間上限
  specialYearlyLimit: number;        // 特別条項年間上限
  special2MonthAvgLimit: number;     // 複数月平均上限
  special6MonthAvgLimit: number;     // 6ヶ月平均上限
  specialMonthlyCountLimit: number;  // 特別条項適用可能月数
  healthMeasures?: string;
  notificationAuthority?: string;
}

export interface ComplianceAlert {
  id: string;
  employeeId: string;
  alertType: 'monthly_overtime_approaching' | 'monthly_overtime_exceeded' | 
            'yearly_overtime_approaching' | 'yearly_overtime_exceeded' |
            'special_limit_approaching' | 'special_limit_exceeded' |
            'health_check_required' | 'continuous_work_violation';
  alertLevel: 'info' | 'warning' | 'critical' | 'emergency';
  targetPeriod: string;           // 対象期間
  currentHours: number;           // 現在の時間外労働時間
  limitHours: number;            // 上限時間
  thresholdPercentage: number;   // アラート発動閾値
  message: string;
  autoGenerated: boolean;
  acknowledged: boolean;
  acknowledgedBy?: string;
  acknowledgedAt?: Date;
  resolved: boolean;
  resolvedAt?: Date;
  resolutionNotes?: string;
  createdAt: Date;
}

export interface ObjectiveTimeRecord {
  id: string;
  employeeId: string;
  recordDate: Date;
  // ICカードデータ
  icCardIn?: Date;
  icCardOut?: Date;
  icCardDeviceId?: string;
  icCardLocation?: string;
  // PCログデータ
  pcLogin?: Date;
  pcLogout?: Date;
  pcDeviceId?: string;
  pcIpAddress?: string;
  // 自己申告データ
  selfReportedIn?: Date;
  selfReportedOut?: Date;
  selfReportReason?: string;
  // 乖離チェック結果
  discrepancyDetected: boolean;
  discrepancyMinutes: number;
  discrepancyExplanation?: string;
  // 最終確定データ
  verifiedIn?: Date;
  verifiedOut?: Date;
  verifiedBy?: string;
  verificationMethod?: 'ic_card' | 'pc_log' | 'manual_review' | 'supervisor_approval';
}

export interface DetailedWorkHours {
  id: string;
  employeeId: string;
  calculationDate: Date;
  regularHours: number;
  actualWorkHours: number;
  dailyOvertime: number;
  weeklyOvertime: number;
  statutoryOvertime: number;      // 法定時間外労働（36協定対象）
  lateNightHours: number;
  holidayWorkHours: number;
  statutoryHolidayHours: number;
  breakMinutes: number;
  breakLawCompliant: boolean;
  agreementCompliant: boolean;
  complianceNotes?: string;
  payrollCalculationId?: string;
}

export interface ComplianceStatus {
  employeeId: string;
  period: string;
  monthlyOvertimeHours: number;
  monthlyLimit: number;
  monthlyComplianceRate: number;   // 遵守率 (0-1)
  yearlyOvertimeHours: number;
  yearlyLimit: number;
  yearlyComplianceRate: number;
  specialLimitUsedCount: number;   // 特別条項使用回数
  specialLimitAvailable: number;   // 特別条項残り回数
  healthCheckRequired: boolean;
  alerts: ComplianceAlert[];
  riskLevel: 'low' | 'medium' | 'high' | 'critical';
}

export class ComplianceEngine {
  private db: Database;

  constructor(database: Database) {
    this.db = database;
  }

  /**
   * 36協定監視 - メイン監視機能
   */
  async monitor36Agreement(employeeId: string, targetDate: Date = new Date()): Promise<ComplianceStatus> {
    const agreement = await this.getCurrentAgreement();
    const currentMonth = this.formatMonth(targetDate);
    const currentYear = targetDate.getFullYear();

    // 月間時間外労働時間の取得
    const monthlyOvertime = await this.getMonthlyOvertimeHours(employeeId, currentMonth);
    
    // 年間時間外労働時間の取得
    const yearlyOvertime = await this.getYearlyOvertimeHours(employeeId, currentYear);
    
    // 特別条項使用回数の取得
    const specialLimitUsedCount = await this.getSpecialLimitUsedCount(employeeId, currentYear);
    
    // コンプライアンス状況の評価
    const complianceStatus = this.evaluateCompliance(
      employeeId,
      agreement,
      monthlyOvertime,
      yearlyOvertime,
      specialLimitUsedCount,
      currentMonth
    );

    // 必要に応じてアラートを生成
    await this.generateComplianceAlerts(complianceStatus, agreement);

    return complianceStatus;
  }

  /**
   * 客観的記録の作成・更新
   */
  async recordObjectiveTime(record: Partial<ObjectiveTimeRecord>): Promise<string> {
    const id = `OBJ_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
    
    return new Promise((resolve, reject) => {
      const sql = `
        INSERT OR REPLACE INTO objective_time_records (
          id, employee_id, record_date,
          ic_card_in, ic_card_out, ic_card_device_id, ic_card_location,
          pc_login, pc_logout, pc_device_id, pc_ip_address,
          self_reported_in, self_reported_out, self_report_reason,
          discrepancy_detected, discrepancy_minutes, discrepancy_explanation,
          verified_in, verified_out, verified_by, verification_method
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      `;
      
      this.db.run(sql, [
        id,
        record.employeeId,
        record.recordDate?.toISOString().split('T')[0],
        record.icCardIn?.toISOString(),
        record.icCardOut?.toISOString(),
        record.icCardDeviceId,
        record.icCardLocation,
        record.pcLogin?.toISOString(),
        record.pcLogout?.toISOString(),
        record.pcDeviceId,
        record.pcIpAddress,
        record.selfReportedIn?.toISOString(),
        record.selfReportedOut?.toISOString(),
        record.selfReportReason,
        record.discrepancyDetected ? 1 : 0,
        record.discrepancyMinutes || 0,
        record.discrepancyExplanation,
        record.verifiedIn?.toISOString(),
        record.verifiedOut?.toISOString(),
        record.verifiedBy,
        record.verificationMethod
      ], function(err: any) {
        if (err) {
          reject(err);
        } else {
          resolve(id);
        }
      });
    });
  }

  /**
   * 自己申告と客観的記録の乖離チェック
   */
  async checkDiscrepancy(employeeId: string, date: Date): Promise<ObjectiveTimeRecord | null> {
    return new Promise((resolve, reject) => {
      const sql = `
        SELECT * FROM objective_time_records 
        WHERE employee_id = ? AND record_date = ?
      `;
      
      this.db.get(sql, [employeeId, date.toISOString().split('T')[0]], (err: any, row: any) => {
        if (err) {
          reject(err);
        } else if (!row) {
          resolve(null);
        } else {
          const record = this.mapObjectiveTimeRecord(row);
          
          // 乖離チェックロジック
          const discrepancy = this.calculateDiscrepancy(record);
          record.discrepancyDetected = discrepancy.detected;
          record.discrepancyMinutes = discrepancy.minutes;
          record.discrepancyExplanation = discrepancy.explanation;
          
          resolve(record);
        }
      });
    });
  }

  /**
   * リアルタイム36協定アラート生成
   */
  async generateRealTimeAlert(employeeId: string, newOvertimeHours: number): Promise<ComplianceAlert[]> {
    const alerts: ComplianceAlert[] = [];
    const agreement = await this.getCurrentAgreement();
    const currentMonth = this.formatMonth(new Date());
    
    // 月間上限チェック
    const monthlyTotal = await this.getMonthlyOvertimeHours(employeeId, currentMonth) + newOvertimeHours;
    
    if (monthlyTotal >= agreement.monthlyOvertimeLimit * 0.8) { // 80%以上で警告
      const alert = await this.createAlert(
        employeeId,
        monthlyTotal >= agreement.monthlyOvertimeLimit ? 'monthly_overtime_exceeded' : 'monthly_overtime_approaching',
        monthlyTotal >= agreement.monthlyOvertimeLimit ? 'critical' : 'warning',
        currentMonth,
        monthlyTotal,
        agreement.monthlyOvertimeLimit,
        80.0
      );
      alerts.push(alert);
    }

    // 健康確保措置チェック（月80時間超）
    if (monthlyTotal >= 80.0) {
      const healthAlert = await this.createAlert(
        employeeId,
        'health_check_required',
        'critical',
        currentMonth,
        monthlyTotal,
        80.0,
        100.0
      );
      alerts.push(healthAlert);
    }

    return alerts;
  }

  /**
   * 詳細労働時間計算
   */
  async calculateDetailedWorkHours(employeeId: string, date: Date): Promise<DetailedWorkHours> {
    const objectiveRecord = await this.getObjectiveRecord(employeeId, date);
    const payrollRules = await this.db.getPayrollRules();
    
    if (!objectiveRecord || !objectiveRecord.verifiedIn || !objectiveRecord.verifiedOut) {
      throw new Error('Verified time records not found');
    }

    const workStart = objectiveRecord.verifiedIn;
    const workEnd = objectiveRecord.verifiedOut;
    const totalMinutes = (workEnd.getTime() - workStart.getTime()) / (1000 * 60);
    const breakMinutes = this.calculateRequiredBreak(totalMinutes / 60);
    const actualWorkHours = (totalMinutes - breakMinutes) / 60;

    // 各種時間外労働の計算
    const dailyOvertime = Math.max(0, actualWorkHours - payrollRules.regularHoursPerDay);
    const weeklyOvertime = await this.calculateWeeklyOvertime(employeeId, date, actualWorkHours);
    const statutoryOvertime = Math.max(dailyOvertime, weeklyOvertime); // 法定時間外労働
    
    // 深夜労働時間の計算
    const lateNightHours = this.calculateLateNightHours(workStart, workEnd);
    
    // 休日労働時間の計算
    const holidayHours = await this.isHoliday(date) ? actualWorkHours : 0;
    const statutoryHolidayHours = await this.isStatutoryHoliday(date) ? actualWorkHours : 0;

    const detailedHours: DetailedWorkHours = {
      id: `DWH_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
      employeeId,
      calculationDate: date,
      regularHours: Math.min(actualWorkHours, payrollRules.regularHoursPerDay),
      actualWorkHours,
      dailyOvertime,
      weeklyOvertime,
      statutoryOvertime,
      lateNightHours,
      holidayWorkHours: holidayHours,
      statutoryHolidayHours,
      breakMinutes,
      breakLawCompliant: this.isBreakCompliant(actualWorkHours, breakMinutes),
      agreementCompliant: statutoryOvertime <= 4.0, // 1日4時間以内なら原則遵守
      complianceNotes: this.generateComplianceNotes(statutoryOvertime, lateNightHours)
    };

    await this.saveDetailedWorkHours(detailedHours);
    return detailedHours;
  }

  // プライベートメソッド群

  private async getCurrentAgreement(): Promise<LaborAgreement> {
    return new Promise((resolve, reject) => {
      const sql = `
        SELECT * FROM labor_agreements 
        WHERE effective_from <= DATE('now') AND effective_to >= DATE('now')
        ORDER BY effective_from DESC LIMIT 1
      `;
      
      this.db.get(sql, [], (err: any, row: any) => {
        if (err) {
          reject(err);
        } else if (!row) {
          // デフォルト協定を返す
          resolve(this.getDefaultAgreement());
        } else {
          resolve(this.mapLaborAgreement(row));
        }
      });
    });
  }

  private async getMonthlyOvertimeHours(employeeId: string, month: string): Promise<number> {
    return new Promise((resolve, reject) => {
      const sql = `
        SELECT COALESCE(SUM(statutory_overtime), 0) as total_overtime
        FROM detailed_work_hours 
        WHERE employee_id = ? AND strftime('%Y-%m', calculation_date) = ?
      `;
      
      this.db.get(sql, [employeeId, month], (err: any, row: any) => {
        if (err) {
          reject(err);
        } else {
          resolve(row?.total_overtime || 0);
        }
      });
    });
  }

  private async getYearlyOvertimeHours(employeeId: string, year: number): Promise<number> {
    return new Promise((resolve, reject) => {
      const sql = `
        SELECT COALESCE(SUM(statutory_overtime), 0) as total_overtime
        FROM detailed_work_hours 
        WHERE employee_id = ? AND strftime('%Y', calculation_date) = ?
      `;
      
      this.db.get(sql, [employeeId, year.toString()], (err: any, row: any) => {
        if (err) {
          reject(err);
        } else {
          resolve(row?.total_overtime || 0);
        }
      });
    });
  }

  private async getSpecialLimitUsedCount(employeeId: string, year: number): Promise<number> {
    return new Promise((resolve, reject) => {
      const sql = `
        SELECT COUNT(*) as count
        FROM detailed_work_hours 
        WHERE employee_id = ? 
        AND strftime('%Y', calculation_date) = ?
        AND statutory_overtime > 45.0
        GROUP BY strftime('%Y-%m', calculation_date)
      `;
      
      this.db.get(sql, [employeeId, year.toString()], (err: any, row: any) => {
        if (err) {
          reject(err);
        } else {
          resolve(row?.count || 0);
        }
      });
    });
  }

  private evaluateCompliance(
    employeeId: string,
    agreement: LaborAgreement,
    monthlyOvertime: number,
    yearlyOvertime: number,
    specialLimitUsedCount: number,
    period: string
  ): ComplianceStatus {
    const monthlyComplianceRate = Math.min(1, monthlyOvertime / agreement.monthlyOvertimeLimit);
    const yearlyComplianceRate = Math.min(1, yearlyOvertime / agreement.yearlyOvertimeLimit);
    
    let riskLevel: 'low' | 'medium' | 'high' | 'critical' = 'low';
    
    if (monthlyOvertime > agreement.monthlyOvertimeLimit || yearlyOvertime > agreement.yearlyOvertimeLimit) {
      riskLevel = 'critical';
    } else if (monthlyComplianceRate > 0.9 || yearlyComplianceRate > 0.9) {
      riskLevel = 'high';
    } else if (monthlyComplianceRate > 0.8 || yearlyComplianceRate > 0.8) {
      riskLevel = 'medium';
    }

    return {
      employeeId,
      period,
      monthlyOvertimeHours: monthlyOvertime,
      monthlyLimit: agreement.monthlyOvertimeLimit,
      monthlyComplianceRate,
      yearlyOvertimeHours: yearlyOvertime,
      yearlyLimit: agreement.yearlyOvertimeLimit,
      yearlyComplianceRate,
      specialLimitUsedCount,
      specialLimitAvailable: agreement.specialMonthlyCountLimit - specialLimitUsedCount,
      healthCheckRequired: monthlyOvertime >= 80.0,
      alerts: [],
      riskLevel
    };
  }

  private async createAlert(
    employeeId: string,
    alertType: ComplianceAlert['alertType'],
    alertLevel: ComplianceAlert['alertLevel'],
    targetPeriod: string,
    currentHours: number,
    limitHours: number,
    thresholdPercentage: number
  ): Promise<ComplianceAlert> {
    const id = `ALERT_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
    const message = this.generateAlertMessage(alertType, currentHours, limitHours);
    
    const alert: ComplianceAlert = {
      id,
      employeeId,
      alertType,
      alertLevel,
      targetPeriod,
      currentHours,
      limitHours,
      thresholdPercentage,
      message,
      autoGenerated: true,
      acknowledged: false,
      resolved: false,
      createdAt: new Date()
    };

    await this.saveAlert(alert);
    return alert;
  }

  private generateAlertMessage(alertType: string, currentHours: number, limitHours: number): string {
    const percentage = Math.round((currentHours / limitHours) * 100);
    
    switch (alertType) {
      case 'monthly_overtime_approaching':
        return `月間時間外労働が上限の${percentage}%に達しました (${currentHours.toFixed(1)}h/${limitHours}h)`;
      case 'monthly_overtime_exceeded':
        return `月間時間外労働上限を超過しました (${currentHours.toFixed(1)}h/${limitHours}h)`;
      case 'yearly_overtime_approaching':
        return `年間時間外労働が上限の${percentage}%に達しました (${currentHours.toFixed(1)}h/${limitHours}h)`;
      case 'yearly_overtime_exceeded':
        return `年間時間外労働上限を超過しました (${currentHours.toFixed(1)}h/${limitHours}h)`;
      case 'health_check_required':
        return `月間時間外労働が80時間を超過しました。医師の面接指導が必要です (${currentHours.toFixed(1)}h)`;
      default:
        return `コンプライアンス警告: ${alertType}`;
    }
  }

  private calculateDiscrepancy(record: ObjectiveTimeRecord): {detected: boolean, minutes: number, explanation: string} {
    let detected = false;
    let minutes = 0;
    let explanation = '';

    // ICカードと自己申告の乖離チェック
    if (record.icCardIn && record.selfReportedIn) {
      const diffIn = Math.abs((record.icCardIn.getTime() - record.selfReportedIn.getTime()) / (1000 * 60));
      if (diffIn > 15) { // 15分以上の乖離
        detected = true;
        minutes = Math.max(minutes, diffIn);
        explanation += `出勤時刻の乖離: ${diffIn.toFixed(0)}分; `;
      }
    }

    if (record.icCardOut && record.selfReportedOut) {
      const diffOut = Math.abs((record.icCardOut.getTime() - record.selfReportedOut.getTime()) / (1000 * 60));
      if (diffOut > 15) {
        detected = true;
        minutes = Math.max(minutes, diffOut);
        explanation += `退勤時刻の乖離: ${diffOut.toFixed(0)}分; `;
      }
    }

    return { detected, minutes, explanation: explanation.trim() };
  }

  private formatMonth(date: Date): string {
    return `${date.getFullYear()}-${(date.getMonth() + 1).toString().padStart(2, '0')}`;
  }

  private calculateRequiredBreak(workHours: number): number {
    if (workHours > 8) return 60;  // 8時間超は60分
    if (workHours > 6) return 45;  // 6時間超は45分
    return 0;
  }

  private isBreakCompliant(workHours: number, actualBreakMinutes: number): boolean {
    const requiredBreak = this.calculateRequiredBreak(workHours);
    return actualBreakMinutes >= requiredBreak;
  }

  private calculateLateNightHours(start: Date, end: Date): number {
    // 22:00-05:00の深夜労働時間を計算
    // 実装省略 - 複雑な時間計算ロジック
    return 0;
  }

  private generateComplianceNotes(overtimeHours: number, lateNightHours: number): string {
    const notes = [];
    if (overtimeHours > 4) notes.push('1日4時間超の時間外労働');
    if (lateNightHours > 0) notes.push(`深夜労働: ${lateNightHours.toFixed(1)}時間`);
    return notes.join(', ');
  }

  // その他のヘルパーメソッドは実装省略...
  private getDefaultAgreement(): LaborAgreement { return {} as LaborAgreement; }
  private mapLaborAgreement(row: any): LaborAgreement { return {} as LaborAgreement; }
  private mapObjectiveTimeRecord(row: any): ObjectiveTimeRecord { return {} as ObjectiveTimeRecord; }
  private async generateComplianceAlerts(status: ComplianceStatus, agreement: LaborAgreement): Promise<void> {}
  private async saveAlert(alert: ComplianceAlert): Promise<void> {}
  private async saveDetailedWorkHours(hours: DetailedWorkHours): Promise<void> {}
  private async getObjectiveRecord(employeeId: string, date: Date): Promise<ObjectiveTimeRecord | null> { return null; }
  private async calculateWeeklyOvertime(employeeId: string, date: Date, dailyHours: number): Promise<number> { return 0; }
  private async isHoliday(date: Date): Promise<boolean> { return false; }
  private async isStatutoryHoliday(date: Date): Promise<boolean> { return false; }
}

export default ComplianceEngine;